
language: go
go:
- 1.4
- 1.5
- 1.6
- 1.7
- 1.8
- 1.9

install:
  - cd $GOPATH/src/github.com/$TRAVIS_REPO_SLUG
  - go get github.com/anacrolix/envpprof
  - go get github.com/anacrolix/tagflag
  - go get github.com/stretchr/testify/assert
  - go build -i -v

script:
  - go test -v
