image:
  - Visual Studio 2017

environment:
  GOPATH: c:\gopath

install:
  - set PATH=%GOPATH%\bin;%PATH%
  - set PATH=C:\go14-x86;%GOPATH%\bin;%PATH%
  - set PATH=C:\msys64\mingw64\bin;%PATH%
  - go version
  - go env
  - go get github.com/anacrolix/envpprof
  - go get github.com/anacrolix/tagflag
  - go get github.com/stretchr/testify/assert

build_script:
  - go build -v -x -a

before_test:
  - go test -v
